### ISSUE TITLE
Way to track API requests

### ISSUE THREAD

**Issue by imrealashu** [ipunkt/laravel-analytics#51]
I've been trying to track events for API requests e.g., `Analytics::trackEvent('Search', 'Filter', 'city')` but  not able to send it to GA since the method isn't rendering the page, just JSON response.
Is there any way to do that? Any suggestions would help.

**Comment by Grayda** [comment]
I had this exact same issue and my solution was to use [this Laravel library](https://github.com/irazasyed/laravel-gamp) for Google Analytics' Measurement Protocol which is designed for situations like this.

Because I was using a trait to abstract out all my analytics, replacing this library with the new one was easy.

**Comment by rokde** [comment]
@Grayda Thank you for your advice. Maybe @imrealashu can use this too. We had no problems yet with our library - but we also built it. :)

**Comment by imrealashu** [comment]
Thanks for the advice @Grayda 
I used [Vue Analytics](https://www.npmjs.com/package/vue-analytics) for the time being to track events on the Vue Components. But [Laravel Gamp](https://github.com/irazasyed/laravel-gamp) looks cool I'll definitely try this out and try to go with your suggestion. Thanks for the suggestion.
